server:
  port: 8801

spring:
  application:
    name: cloud-stream-rabbit-provider
  cloud:
    stream:
      # 在此处配置要绑定的RabbitMQ的服务信息
      binders:
        # 表示定义的名称，用于binding的整合
        defaultRabbit:
          # 消息组件类型
          type: rabbit
          # 配置RabbitMQ连接环境
          environment:
            host: localhost
            port: 5672
            username: guest
            password: guest
      # 服务的整合处理
      bindings:
        # <binding name> 绑定的通道名
        output:
          # 表示Exchange名称，交换模式默认是topic
          destination: studyExchange
          # 设置消息类型，本次为json
          content-type: application/json

eureka:
  client:
    # 表示是否将自己注册进EurekaServer，默认为true
    register-with-eureka: true
    # 是否从EurekaServer中抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合Ribbon使用负载均衡
    fetch-registry: true
    # 设置与EurekaServer交互的地址，检查服务和注册服务都需要依赖这个地址
    service-url:
      # 注册到集群注册中心
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      # 单机版
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    # 访问路径可以显示IP地址
    prefer-ip-address: true
    instance-id: streamProvider8801