server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: qwer1234
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hamish.springcloud.entitys  #所有entity实体类所在包

eureka:
  client:
    # 表示是否将自己注册进EurekaServer，默认为true
    register-with-eureka: true
    # 是否从EurekaServer中抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合Ribbon使用负载均衡
    fetch-registry: true
    # 设置与EurekaServer交互的地址，检查服务和注册服务都需要依赖这个地址
    service-url:
      # 注册到集群注册中心
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    # 访问路径可以显示IP地址
    prefer-ip-address: true
    instance-id: payment8001
    # Eureka客户端向服务端发送心跳的时间间隔，单位为秒，默认30s
    lease-renewal-interval-in-seconds: 1
    # Eureka在收到最后一次心跳后等待时间上限，单位为秒，默认90秒，超时将剔除服务
    lease-expiration-duration-in-seconds: 2
