server:
  port: 9901

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能，利用微服务名创建路由
          enabled: true
      routes:
        # 路由ID，没有固定规则，但要求唯一，建议配合服务名
        - id: payment_route1
          # 匹配后提供服务的路由地址
          #uri: http://localhost:8001
          uri: http://cloud-payment-service
          # 断言：
          predicates:
            # 路径相匹配进行路由
            - Path=/payment/**
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]


eureka:
  client:
    # 表示是否将自己注册进EurekaServer，默认为true
    register-with-eureka: true
    # 是否从EurekaServer中抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合Ribbon使用负载均衡
    fetch-registry: true
    # 设置与EurekaServer交互的地址，检查服务和注册服务都需要依赖这个地址
    service-url:
      # 注册到集群注册中心
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      # 单机版
      defaultZone: http://eureka7001.com:7001/eureka,
  instance:
    # 访问路径可以显示IP地址
    prefer-ip-address: true
    instance-id: gateway9901
