server:
  port: 80

spring:
  application:
    name: cloud-feign-order-service

eureka:
  client:
    # 表示是否将自己注册进EurekaServer，默认为true
    register-with-eureka: true
    # 是否从EurekaServer中抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合Ribbon使用负载均衡
    fetch-registry: true
    # 设置与EurekaServer交互的地址，检查服务和注册服务都需要依赖这个地址
    service-url:
      # 注册到集群注册中心
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    # 访问路径可以显示IP地址
    prefer-ip-address: true
    instance-id: feignOrder80

logging:
  level:
    # feign日志以什么级别监控那个接口
    com.hamish.springcloud.service.FeignOrderService: debug
